version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: spin_task
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
