<?php
//Class generated by Adenagbe Emmanuel on 11/08/2024
namespace App\Http\Repositories;

use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class UserRepository
{
    /**
     * @throws Exception
     */
    public function all(array $filters = [], array $columns = ['*'], array $with = [], $perPage = 15, $limit = null)
    {
        $query = User::query();

        // Apply filters based on $filters array
        foreach ($filters as $column => $value) {
            $query->where($column, $value);
        }

        $query->select($columns);

        if ($with) {
            $query->with($with); // Eager load related models
        }

        try {
            if ($limit) {
                $query->limit($limit);

                return $query->get();
            } else {
                return $query->paginate($perPage);
            }
        } catch (ModelNotFoundException $e) {
            // Handle the case where no users are found based on filters
            throw new Exception('No ', 0, $e);
        } catch (Exception $e) {
            throw new Exception($e, 0, $e);
        }
    }

    public function find($id, array $columns = ['*'], array $with = [])
    {
        $query = User::query();
        $query->select($columns);

        if ($with) {
            $query->with($with); // Eager load related models
        }

        if (is_array($id)) {
            return $query->whereIn('id', $id)->get();
        } else {
            // Check if ID is numeric before using find
            if (($id)) {
                return $query->find($id);
            } else {
                // Throw a more informative exception with context
                throw new InvalidArgumentException('User ID must be a positive numeric value. Received: ' . $id);
            }
        }
    }

    public function findWhere($column, $value, array $columns = ['*'], array $with = []): Model|Builder|null
    {
        $query = User::query();
        $query->select($columns);

        if ($with) {
            $query->with($with); // Eager load related models
        }

        try {
            return $query->where($column, $value)->first();
        } catch (ModelNotFoundException $e) {
            // Handle the case where no user is found with the specified criteria
            throw new ModelNotFoundException('User not found with');
        }
    }

    public function findWhereWithArray(array $conditions, array $columns = ['*'], array $with = []): Model|Builder|null
    {
        $query = User::query();
        $query->select($columns);

        if ($with) {
            $query->with($with); // Eager load related models
        }

        foreach ($conditions as $column => $value) {
            $query->where($column, $value);
        }

        try {
            return $query->first();
        } catch (ModelNotFoundException $e) {
            // Handle the case where no article is found with the specified criteria
            throw new ModelNotFoundException('User not found with the given criteria');
        }
    }


    /**
     * @throws Exception
     */
    public function create(array $data)
    {
        try {
            return User::create($data);
        } catch (Exception $e) {
            // Handle potential validation or data saving errors (consider logging)
            throw new Exception('An error occurred while creating a new User.', 0, $e);
        }
    }

    /**
     * @throws Exception
     */
    public function update(array $data, string $id)
    {
        $user = User::find($id);
        if (!$user) {
            // Handle the case where the user to update is not found
            throw new Exception('User resource not found, please contact the administrator', 404);
        }
        $user->forceFill($data);
        $user->save();

        return $user;
    }

    /**
     * @throws Exception
     */
    public function delete($id): string
    {
        try {
            return User::destroy($id);
        } catch (Exception $e) {
            // Handle potential deletion errors (consider logging)
            throw new Exception('An error occurred while deleting the User.', 0, $e);
        }
    }

    public function check($column, $value)
    {
        return User::where($column, $value)->exists();
    }

    public function getMe()
    {
        return $this->find(auth()->id(), ['*']);
    }
}
